# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VO.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1061, 771)
        self.gobacktomain_button = QtWidgets.QPushButton(Dialog)
        self.gobacktomain_button.setGeometry(QtCore.QRect(20, 10, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gobacktomain_button.setFont(font)
        self.gobacktomain_button.setObjectName("gobacktomain_button")
        self.gotovo_button = QtWidgets.QPushButton(Dialog)
        self.gotovo_button.setGeometry(QtCore.QRect(120, 10, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.gotovo_button.setFont(font)
        self.gotovo_button.setObjectName("gotovo_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.gobacktomain_button.setText(_translate("Dialog", "Calibrate"))
        self.gotovo_button.setText(_translate("Dialog", "VO"))
